version: "3.9"
services:
  api:
    build: ./api
    expose:
      - 8080
    ports:
      - 8080:8080
    volumes:
      - ./api/:/app
      - /app/target
    depends_on:
      - redis
      - postgres
    env_file:
      - .env
    # command: cargo run

  frontend:
    build: ./frontend
    expose:
      - 3000
    ports:
      - 3000:3000
    volumes:
      - ./frontend/:/app
      - /frontend/node_modules
    depends_on:
      - api
    # command: npm run dev

  redis:
    image: "redis"

  db:
    image: postgres
    restart: always
    env_file:
      - .env
      
  adminer:
    image: adminer
    restart: always
    ports:
      - 8000:8080